parameters = [
    # 搜药接口入参0
    {
        "memberId": "",
        "isSuper": "0",
        "dtpOrCommon": "2",
        "keywords": "keywords1",
        "scanResult": ""
    },
    #推药接口入参1
    {
        "ourGroupIds": [],
        "memberIds": ["16236586"],
        "drugs": [{
            "isRule": "0",
            "originalPrice": "35.20",
            "pack": "",
            "money": "70.40",
            "commonFullPinyin": "{\\\"commonFullPinyin\\\":\\\"ganmaolingjiaonang\\\",\\\"memberPrice\\\":\\\"35.20\\\",\\\"originalPrice\\\":\\\"35.20\\\",\\\"image\\\":\\\"https:\\\\/\\\\/uniondrug-release.oss-cn-shanghai.aliyuncs.com\\\\/oss\\\\/upload\\\\/file\\\\/goods\\\\/1586484073064.jpg\\\",\\\"attrs\\\":\\\"\\\",\\\"cates\\\":\\\"\\\",\\\"skuNo\\\":\\\"635-2143451\\\",\\\"realName\\\":null,\\\"goodsType\\\":1,\\\"goodsSubType\\\":11}",
            "image": "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484073064.jpg",
            "count": "2",
            "approvalNumber": "国药准字Z20055271",
            "tradeCode": "6923718120188",
            "activityType": "",
            "manufacturer": "",
            "id": "",
            "internalId": "2143451",
            "commonName": "感冒灵胶囊",
            "quantity": "2",
            "isSuper": "0",
            "memberPrice": "35.20",
            "pointMsg": "",
            "unitPrice": "35.20",
            "isRx": "0",
            "form": "",
            "isDrug": "1"
        }],
        "pushType": "2",
        "isSendCoupon": "1"
    },
    #加购物车2
    {
        "signCartText": "counselor",
        "longitude": "",
        "specializeSearch": "",
        "supplyEshop": "1",
        "showDrugName": "0",
        "isGather": "1",
        "batchId": "62c2d0df83b5e"
    },
    # 清空购物车3
    {
        "products": [
            {
                "scene": "1",
                "isPreTime": "",
                "sourceTradeCode": "76655f30a1f15ae0e192fb59e4c09b67",
                "showName": "加劲 感冒灵胶囊",
                "shops": [
                    {
                        "isColdChain": "0",
                        "isDtp": "0",
                        "tradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                        "drugName": "感冒灵胶囊",
                        "commonName": "感冒灵胶囊",
                        "brand": "加劲",
                        "price": "35.20",
                        "img": [
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484073064.jpg",
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484068569.jpg",
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484083347.jpg"
                        ],
                        "manufacturer": "",
                        "approvalNumber": "国药准字Z20055271",
                        "description": "",
                        "isPrescription": False,
                        "projectId": "2",
                        "merchantId": "635",
                        "merchantStatus": "1",
                        "merchantIsPrescription": "1",
                        "storeId": "7590",
                        "shopStatus": "1",
                        "storeDomestic": "1",
                        "storeRider": "1",
                        "expressType": "0",
                        "storeOnlySelf": "1",
                        "storeDistance": "3.0",
                        "storeStartTime": "00:00:00",
                        "storeEndTime": "23:59:59",
                        "goodsInternalId": "2143451",
                        "realTradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                        "realCommonName": "感冒灵胶囊",
                        "form": "",
                        "pack": "",
                        "sales": "",
                        "channel": "2",
                        "distance": "",
                        "scene": "1",
                        "goodsSignType": "counselor",
                        "goodsSubType": "11",
                        "goodsType": "1",
                        "isOffShelf": False,
                        "attrs": [],
                        "cates": []
                    }
                ],
                "isColdChain": "0",
                "isDtp": "0",
                "tradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                "drugName": "感冒灵胶囊",
                "commonName": "感冒灵胶囊",
                "brand": "加劲",
                "price": "35.20",
                "img": [
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484073064.jpg",
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484068569.jpg",
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484083347.jpg"
                ],
                "manufacturer": "",
                "approvalNumber": "国药准字Z20055271",
                "description": "",
                "isPrescription": False,
                "projectId": "2",
                "merchantId": "0",
                "merchantStatus": "1",
                "merchantIsPrescription": "1",
                "storeId": "0",
                "shopStatus": "1",
                "storeDomestic": "1",
                "storeRider": "1",
                "expressType": "0",
                "storeOnlySelf": "1",
                "storeDistance": "3.0",
                "storeStartTime": "",
                "storeEndTime": "",
                "goodsInternalId": "",
                "realTradeCode": "",
                "realCommonName": "感冒灵胶囊",
                "form": "",
                "pack": "",
                "sales": "0",
                "channel": "2",
                "distance": "",
                "goodsSignType": "counselor",
                "goodsSubType": "11",
                "goodsType": "1",
                "isOffShelf": False,
                "attrs": [],
                "cates": [],
                "isDisplay": True,
                "createTime": "1656934811",
                "selectForm": "",
                "quantity": "1",
                "check": True
            }
        ],
        "signCartText": "counselor",
        "location": "118.779047,31.972011",
        "batchId": "62c2d0df83b5e"
    },
    #创建预订单 createPreviewOrder4
    {
        "sellFrom": "",
        "sellLabel": "",
        "tid": "",
        "contractFulfillmentId": "",
        "subStationId": "",
        "items": [
            {
                "scene": "1",
                "isPreTime": "",
                "sourceTradeCode": "76655f30a1f15ae0e192fb59e4c09b67",
                "showName": "加劲 感冒灵胶囊",
                "shops": [
                    {
                        "isColdChain": "0",
                        "isDtp": "0",
                        "tradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                        "drugName": "感冒灵胶囊",
                        "commonName": "感冒灵胶囊",
                        "brand": "加劲",
                        "price": "35.20",
                        "img": [
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484073064.jpg",
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484068569.jpg",
                            "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484083347.jpg"
                        ],
                        "manufacturer": "",
                        "approvalNumber": "国药准字Z20055271",
                        "description": "",
                        "isPrescription": False,
                        "projectId": "2",
                        "merchantId": "635",
                        "merchantStatus": "1",
                        "merchantIsPrescription": "1",
                        "storeId": "7590",
                        "shopStatus": "1",
                        "storeDomestic": "1",
                        "storeRider": "1",
                        "expressType": "0",
                        "storeOnlySelf": "1",
                        "storeDistance": "3.0",
                        "storeStartTime": "00:00:00",
                        "storeEndTime": "23:59:59",
                        "goodsInternalId": "2143451",
                        "realTradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                        "realCommonName": "感冒灵胶囊",
                        "form": "",
                        "pack": "",
                        "sales": "",
                        "channel": "2",
                        "distance": "",
                        "scene": "1",
                        "goodsSignType": "counselor",
                        "goodsSubType": "11",
                        "goodsType": "1",
                        "isOffShelf": False,
                        "attrs": [],
                        "cates": []
                    }
                ],
                "isColdChain": "0",
                "isDtp": "0",
                "tradeCode": "E1Np%2FLcsKyjsDT3%2FbewP9QtyW%2Bkw",
                "drugName": "感冒灵胶囊",
                "commonName": "感冒灵胶囊",
                "brand": "加劲",
                "price": "35.20",
                "img": [
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484073064.jpg",
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484068569.jpg",
                    "https://uniondrug-release.oss-cn-shanghai.aliyuncs.com/oss/upload/file/goods/1586484083347.jpg"
                ],
                "manufacturer": "",
                "approvalNumber": "国药准字Z20055271",
                "description": "",
                "isPrescription": False,
                "projectId": "2",
                "merchantId": "0",
                "merchantStatus": "1",
                "merchantIsPrescription": "1",
                "storeId": "0",
                "shopStatus": "1",
                "storeDomestic": "1",
                "storeRider": "1",
                "expressType": "0",
                "storeOnlySelf": "1",
                "storeDistance": "3.0",
                "storeStartTime": "",
                "storeEndTime": "",
                "goodsInternalId": "",
                "realTradeCode": "",
                "realCommonName": "感冒灵胶囊",
                "form": "",
                "pack": "",
                "sales": "0",
                "channel": "2",
                "distance": "",
                "goodsSignType": "counselor",
                "goodsSubType": "11",
                "goodsType": "1",
                "isOffShelf": False,
                "attrs": [],
                "cates": [],
                "isDisplay": True,
                "createTime": "1656934811",
                "selectForm": "",
                "quantity": "1",
                "check": True
            }
        ],
        "addressId": "103878",
        "resource": 2,
        "merchantId": "635",
        "storeId": "7590",
        "selectActivityId":"",
        "selectEquityId": "",
        "selectCardId": "",
        "memberId": "16236586",
        "openid": "oylyluNSviSUzJFliUZuqiArbncU",
        "wxMemberId": "16236586",
        "longitude": "118.779047",
        "latitude": "31.972011",
        "batchId": "62c2d0df83b5e"
    },
    #创建订单5
    {
        "requestNo": "5cbacecc0de1e876504f456497710156"
    },
    #支付接口入参6
    {"paymentNo": 2022070101432331073,
                "accountId": 0,
                "methodCode": "CWXPAY",
                "openid": "oylyluNSviSUzJFliUZuqiArbncU",
                "tradeType": "",
                "bankType": "",
                "totalFee": "0.01",
                "cashFee": "0.01",
                "transactionId": "220418124017062801",
                "outTradeNo": 92070101603664361673,
                "timeEnd": "2022-07-01 15:24:20",
                "refundId": "",
                "outRefundNo": "",
                "tradeStatus": "",
                "refundAmount": "",
                "gmtRefund": "",
                "paymentType": "PD",
                "traceNo": ""},
    #查询线上门店列表7
    {
        "page":1,
        "limit":10,
        "isOffline":0,
        "merchantId":"635",
        "storeName":"",
        "internalId":"",
        "status":"-1",
        "cityName":"",
        "areaName":"",
        "provinceName":"",
        "expressStatus":"-1",
        "organizationId":"7590",
        "isInsuranceMember":"",
        "fullExpress":"",
        "isLogisticInfoComplete":""
    },
    #停用线上门店8
    {
        "isOffline": "1",
        "organizationIds": [
            "7590"
        ]
    },
    #开启线上门店9
    {
        "organizationIds": [
            "7590"
        ],
        "isOffline": "0"
    },
    #完善用药人信息10
    {
        "orderTemperature":{
            "name":"樊战岗",
            "idCard":"610523199201086936",
            "mobile":"18354299687",
            "symptom":"无",
            "temperature":"35",
            "isRisk":"0",
            "trolleyId":"0",
            "mobileWithStar":"183****9687"
        },
        "requestNo":"20d5a05630e506b065e49a70879d9b32",
        "isUpdateRemark":"1"
    },
    #重置下单信息11
    {
        "requestNo": "d7918f40d4411401902de9176590e057",
        "longitude": "",
        "latitude": ""
    }


]

