# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FirstPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 309)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(11, 13, 162, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.barCode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.barCode.setObjectName("barCode")
        self.verticalLayout.addWidget(self.barCode)
        self.qrCode = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.qrCode.setObjectName("qrCode")
        self.verticalLayout.addWidget(self.qrCode)
        self.sshTunnel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.sshTunnel.setObjectName("sshTunnel")
        self.verticalLayout.addWidget(self.sshTunnel)
        self.autoCaseRun = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.autoCaseRun.setObjectName("autoCaseRun")
        self.verticalLayout.addWidget(self.autoCaseRun)
        self.autoCaseMake = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.autoCaseMake.setObjectName("autoCaseMake")
        self.verticalLayout.addWidget(self.autoCaseMake)
        self.checkUpdate = QtWidgets.QPushButton(self.centralwidget)
        self.checkUpdate.setGeometry(QtCore.QRect(390, 10, 112, 32))
        self.checkUpdate.setObjectName("checkUpdate")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 22))
        self.menubar.setObjectName("menubar")
        self.menuRedBull = QtWidgets.QMenu(self.menubar)
        self.menuRedBull.setObjectName("menuRedBull")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuRedBull.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.barCode.setText(_translate("MainWindow", "条形码生成"))
        self.qrCode.setText(_translate("MainWindow", "二维码生成"))
        self.sshTunnel.setText(_translate("MainWindow", "SSH通道"))
        self.autoCaseRun.setText(_translate("MainWindow", "自动化测试本地执行"))
        self.autoCaseMake.setText(_translate("MainWindow", "自动化测试用例生成"))
        self.checkUpdate.setText(_translate("MainWindow", "检查更新"))
        self.menuRedBull.setTitle(_translate("MainWindow", "RedBull"))
